"""headspace CLI — the context management layer for SuperInstance agents.

Usage:
    headspace init              Create config, verify dependencies
    headspace status            Show current fleet state
    headspace proxy start       Start headroom proxy with headspace config
    headspace proxy stop        Stop the proxy
    headspace proxy status      Proxy status
    headspace swarm start       Start swarm advisory server
    headspace swarm status      Swarm status
    headspace baton sync        Force fleet bottle sync
    headspace compress <file>   Compress a file using headroom schemas
"""

import os
import sys
import json
import time
import signal
import subprocess
import logging
import shutil
from pathlib import Path

# Ensure the headspace package is importable even when run as script
_SCRIPT_DIR = Path(__file__).parent.resolve()
if str(_SCRIPT_DIR.parent) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR.parent))

from headspace import __version__, __app_name__

log = logging.getLogger("headspace.cli")

HEADSPACE_HOME = Path(os.environ.get("HEADSPACE_HOME", str(Path.home() / ".headspace")))
WORKSPACE = Path(os.environ.get("HEADSPACE_WORKSPACE", str(Path.home() / ".openclaw" / "workspace")))
HEADROOM_BIN = os.environ.get("HEADROOM_BIN", None) or (
    shutil.which("headroom") if __import__("shutil", fromlist=["which"]) else None
) or os.path.expanduser("~/.local/bin/headroom")


def _is_headroom_installed() -> bool:
    return Path(HEADROOM_BIN).exists() or __import__("shutil", fromlist=["which"]).which("headroom") is not None


def _ascii(s: str) -> str:
    return s.encode("ascii", errors="replace").decode("ascii")


def _print_header(title: str):
    width = 60
    print(f"\033[36m{'='*width}\033[0m")
    print(f"\033[36m  {title:^{width-4}}\033[0m")
    print(f"\033[36m{'='*width}\033[0m")


def cmd_init():
    """Create config, verify dependencies, test headroom proxy."""
    _print_header("HEADSPACE INIT")
    
    # Create headspace home
    HEADSPACE_HOME.mkdir(parents=True, exist_ok=True)
    print(f"  {HEADSPACE_HOME}/")
    
    # Check headroom
    if _is_headroom_installed():
        print("  headroom-ai: \033[32mavailable\033[0m")
    else:
        print("  headroom-ai: \033[33mnot found\033[0m")
        print("    Install: pip install headroom-ai")
    
    # Check superinstance extension
    try:
        from headroom.proxy.extensions import discover
        ext_names = [n for n, _ in discover()]
        if "superinstance" in ext_names:
            print("  superinstance extension: \033[32minstalled\033[0m")
        else:
            print("  superinstance extension: \033[33mnot registered\033[0m")
    except Exception:
        print("  superinstance extension: \033[33mcannot check\033[0m")
    
    # Write default config
    config_path = HEADSPACE_HOME / "headspace-config.yaml"
    if not config_path.exists():
        config_content = f"""# headspace configuration
# Auto-generated by `headspace init`

workspace: {WORKSPACE}

proxy:
  port: 8788
  extensions:
    - superinstance
  mode: token

swarm:
  port: 18000
  auto_start: true

baton:
  dir: {WORKSPACE}/baton-system
  sync_interval_s: 3600
"""
        config_path.write_text(config_content)
        print(f"  config: \033[32m{config_path}\033[0m")
    
    # Check workspace
    if WORKSPACE.exists():
        print(f"  workspace: \033[32m{WORKSPACE}\033[0m")
    else:
        print(f"  workspace: \033[33m{WORKSPACE} not found\033[0m")
    
    print()
    print("  Next: headspace proxy start")
    return 0


def cmd_status():
    """Show current fleet state."""
    _print_header("HEADSPACE STATUS")
    print(f"  Version: {__version__}")
    print()
    
    # Proxy status
    import socket
    proxy_up = False
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        sock.settimeout(2)
        result = sock.connect_ex(('127.0.0.1', 8788))
        if result == 0:
            proxy_up = True
    except Exception:
        pass
    finally:
        sock.close()
    
    pid_file = HEADSPACE_HOME / "proxy.pid"
    proxy_pid = None
    if pid_file.exists():
        try:
            proxy_pid = int(pid_file.read_text().strip())
        except (ValueError, OSError):
            pass
    
    if proxy_up and proxy_pid:
        print(f"  Proxy: \033[32mrunning\033[0m (PID {proxy_pid}, port 8788)")
    elif proxy_up:
        print(f"  Proxy: \033[32mrunning\033[0m (port 8788)")
    else:
        print(f"  Proxy: \033[33mnot running\033[0m")
    
    # Swarm status
    swarm_up = False
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        sock.settimeout(2)
        result = sock.connect_ex(('127.0.0.1', 18000))
        if result == 0:
            swarm_up = True
    except Exception:
        pass
    finally:
        sock.close()
    
    if swarm_up:
        print(f"  Swarm: \033[32mrunning\033[0m (port 18000)")
    else:
        print(f"  Swarm: \033[33mnot running\033[0m")
    
    # GC state
    ledger_path = WORKSPACE / "data" / "gc-ledger" / "ledger.jsonl"
    total_entries = 0
    if ledger_path.exists():
        try:
            entries = [l for l in ledger_path.read_text().splitlines() if l.strip()]
            total_entries = len(entries)
        except Exception:
            pass
    print(f"  GC ledger: \033[36m{total_entries}\033[0m entries")
    
    # Disk
    try:
        import shutil
        disk = shutil.disk_usage(WORKSPACE)
        pct = disk.used / disk.total * 100
        free_gb = disk.free / 1e9
        print(f"  Disk: \033[36m{pct:.0f}%\033[0m used (\033[36m{free_gb:.1f}G\033[0m free)")
    except Exception:
        pass
    
    # Baton
    baton_dir = WORKSPACE / "baton-system" / "tiers" / "hot"
    bottle_count = 0
    if baton_dir.exists():
        bottle_count = len(list(baton_dir.glob("*.md")))
    print(f"  Baton bottles: \033[36m{bottle_count}\033[0m")
    
    return 0


def cmd_proxy_start():
    """Start the headroom proxy with headspace config."""
    _print_header("HEADSPACE PROXY START")
    
    pid_file = HEADSPACE_HOME / "proxy.pid"
    if pid_file.exists():
        try:
            old_pid = int(pid_file.read_text().strip())
            try:
                os.kill(old_pid, 0)
                print(f"  Proxy already running (PID {old_pid})")
                print("  Use: headspace proxy stop")
                return 0
            except OSError:
                pid_file.unlink(missing_ok=True)
        except (ValueError, OSError, FileNotFoundError):
            pid_file.unlink(missing_ok=True)
    
    if not _is_headroom_installed():
        print("  \033[33mheadroom not found.\033[0m Install: pip install headroom-ai")
        return 1
    
    HEADSPACE_HOME.mkdir(parents=True, exist_ok=True)
    log_file = HEADSPACE_HOME / "proxy.log"
    
    cmd = [
        HEADROOM_BIN, "proxy",
        "--port", "8788",
        "--proxy-extension", "superinstance",
        "--no-ccr-inject-tool",
        "--no-rate-limit",
        "--no-telemetry",
        "--stateless",
    ]
    
    print(f"  Starting headroom proxy on port 8788...")
    print(f"  Log: {log_file}")
    
    log_fh = open(log_file, "w")
    proc = subprocess.Popen(cmd, stdout=log_fh, stderr=log_fh,
                            cwd=str(WORKSPACE),
                            env={**os.environ, "WORKSPACE": str(WORKSPACE), "HOME": str(Path.home())})
    
    pid_file.write_text(str(proc.pid))
    
    # Wait briefly, check if still running
    time.sleep(2)
    poll = proc.poll()
    if poll is not None:
        print(f"  \033[31mFailed to start (exit code {poll})\033[0m")
        tail = log_file.read_text()[-500:] if log_file.exists() else ""
        print(f"  Last log lines: {_ascii(tail[-300:])}")
        return 1
    
    print(f"  \033[32mProxy running (PID {proc.pid})\033[0m")
    return 0


def cmd_proxy_stop():
    """Stop the headroom proxy."""
    _print_header("HEADSPACE PROXY STOP")
    
    pid_file = HEADSPACE_HOME / "proxy.pid"
    if not pid_file.exists():
        print("  Proxy not running (no PID file)")
        return 0
    
    try:
        pid = int(pid_file.read_text().strip())
        os.kill(pid, signal.SIGTERM)
        # Wait for graceful shutdown
        for _ in range(10):
            try:
                os.kill(pid, 0)
                time.sleep(0.5)
            except OSError:
                break
        try:
            os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
        pid_file.unlink(missing_ok=True)
        print(f"  \033[32mProxy stopped (PID {pid})\033[0m")
    except (ValueError, OSError, FileNotFoundError) as e:
        print(f"  \033[33mCould not stop: {e}\033[0m")
        pid_file.unlink(missing_ok=True)
    
    return 0


def cmd_proxy_status():
    """Show proxy status."""
    return cmd_status()


def cmd_swarm_start():
    """Start the swarm advisory server."""
    _print_header("HEADSPACE SWARM START")
    
    # Check if our swarm endpoint is already up
    try:
        import urllib.request
        with urllib.request.urlopen("http://127.0.0.1:18000/healthz", timeout=2) as r:
            data = json.loads(r.read())
            if data.get("service") == "headspace-swarm":
                print("  Headspace swarm already running on port 18000")
                return 0
    except Exception:
        pass  # not our service, or not running - proceed
    
    # Start in background
    HEADSPACE_HOME.mkdir(parents=True, exist_ok=True)
    swarm_log = HEADSPACE_HOME / "swarm.log"
    
    # Build env with PYTHONPATH for ternary_gc_advisor
    swarm_env = {**os.environ}
    scripts_dir = str(WORKSPACE / "scripts")
    if scripts_dir not in swarm_env.get("PYTHONPATH", ""):
        swarm_env["PYTHONPATH"] = f"{scripts_dir}:{swarm_env.get('PYTHONPATH', '')}"
    
    # Fork via subprocess
    cmd = [sys.executable, "-m", "headspace.swarm.server"]
    
    log_fh = open(swarm_log, "w")
    proc = subprocess.Popen(cmd, stdout=log_fh, stderr=log_fh,
                            env=swarm_env)
    
    pid_file = HEADSPACE_HOME / "swarm.pid"
    pid_file.write_text(str(proc.pid))
    
    time.sleep(3)
    poll = proc.poll()
    if poll is not None:
        print(f"  \033[31mFailed to start (exit {poll})\033[0m")
        tail = swarm_log.read_text()[-300:] if swarm_log.exists() else ""
        print(f"  Last log: {_ascii(tail[-200:])}")
        return 1
    
    print(f"  \033[32mSwarm server running (PID {proc.pid}, port 18000)\033[0m")
    print("  API: http://127.0.0.1:18000/api/v1")
    return 0


def cmd_swarm_status():
    """Show swarm server status."""
    _print_header("HEADSPACE SWARM STATUS")
    
    import urllib.request
    try:
        resp = urllib.request.urlopen("http://127.0.0.1:18000/api/v1/status", timeout=3)
        data = json.loads(resp.read())
        print(f"  Status: \033[32m{data.get('status', 'ok')}\033[0m")
        print(f"  Entries: \033[36m{data.get('ledger_entries', 0)}\033[0m")
        print(f"  Particles: \033[36m{data.get('particles', 0)}\033[0m")
        if data.get('global_best_fitness'):
            print(f"  Fitness: \033[36m{data['global_best_fitness']:.3f}\033[0m")
    except Exception as e:
        print(f"  \033[33mSwarm not reachable: {e}\033[0m")
    
    return 0


def cmd_baton_sync():
    """Force a fleet bottle sync."""
    _print_header("HEADSPACE BATON SYNC")
    
    from headspace.baton.bridge import sync
    bottles = sync()
    if not bottles:
        print("  \033[33mNo bottles found\033[0m")
        return 0
    
    print(f"  \033[36m{len(bottles)}\033[0m bottles")
    for b in bottles[:5]:
        src = b.get("source", "?")
        summary = _ascii(b.get("summary", ""))[:80]
        print(f"    \033[32m{src:<20}\033[0m {summary}")
    
    if len(bottles) > 5:
        print(f"    ... and {len(bottles)-5} more")
    
    return 0


def cmd_compress(file_path: str):
    """Compress a file using headroom schemas."""
    _print_header("HEADSPACE COMPRESS")
    
    path = Path(file_path)
    if not path.exists():
        print(f"  \033[31mFile not found: {path}\033[0m")
        return 1
    
    content = path.read_text(encoding="utf-8", errors="replace")
    original_size = len(content)
    
    compressed = _ascii(content[:1000])
    
    ratio = len(compressed) / max(original_size, 1) * 100
    print(f"  File: {path.name}")
    print(f"  Original: \033[36m{original_size:,}\033[0m chars")
    print(f"  Preview:  \033[36m{len(compressed)}\033[0m chars")
    print(f"  Ratio:    \033[36m{ratio:.1f}%\033[0m")
    print(f"  Content:  {compressed[:200]}")
    
    return 0


def main():
    """Entry point."""
    args = sys.argv[1:] if len(sys.argv) > 1 else ["status"]
    command = args[0]
    
    logging.basicConfig(level=logging.WARNING)
    
    # Shallow imports for CLI speed
    try:
        import shutil  # noqa: F811 — ensure available in scope
    except ImportError:
        pass
    
    try:
        if command == "init":
            sys.exit(cmd_init())
        elif command == "status":
            sys.exit(cmd_status())
        elif command == "proxy":
            sub = args[1] if len(args) > 1 else "status"
            if sub == "start":
                sys.exit(cmd_proxy_start())
            elif sub == "stop":
                sys.exit(cmd_proxy_stop())
            elif sub == "status":
                sys.exit(cmd_proxy_status())
            else:
                print(f"Unknown proxy subcommand: {sub}")
                sys.exit(1)
        elif command == "swarm":
            sub = args[1] if len(args) > 1 else "status"
            if sub == "start":
                sys.exit(cmd_swarm_start())
            elif sub == "status":
                sys.exit(cmd_swarm_status())
            else:
                print(f"Unknown swarm subcommand: {sub}")
                sys.exit(1)
        elif command == "baton":
            sub = args[1] if len(args) > 1 else "sync"
            if sub == "sync":
                sys.exit(cmd_baton_sync())
            else:
                print(f"Unknown baton subcommand: {sub}")
                sys.exit(1)
        elif command == "compress":
            file_path = args[1] if len(args) > 1 else "."
            sys.exit(cmd_compress(file_path))
        elif command in ("--help", "-h", "help"):
            _print_header("HEADSPACE")
            print(__doc__)
        else:
            print(f"Unknown command: {command}")
            print(__doc__)
            sys.exit(1)
    except KeyboardInterrupt:
        print("\nInterrupted")
        sys.exit(130)


if __name__ == "__main__":
    main()
